ekino/EkinoNewRelicBundle

Twig/NewRelicExtension.php
Actually the definition of twig functions needs to be the other way around, will not work like it is right now and I just noticed this now... Sorry for that
=> Fix twig method definition

Command/NotifyDeploymentCommand.php, DependencyInjection/Configuration.php, DependencyInjection/EkinoNewRelicExtension.php, NewRelic/NewRelic.php, README.md, Resources/config/services.xml, Resources/recipes/newrelic.rb, Tests/DependencyInjection/ConfigurationTest.php
Got HTTP 422 while "notify deployment" if using roll-up naming strategy, eg. "MyApp1;MyApp".
>The answer from New Relic support:
>The naming technique where you separate the two 'application' names with a semicolon is a technique that is used by the agent in it's configuration files or api calls. It does not carry over into the Data Rest API, however. If you want the deployment to be inserted for both applications it will be necessary to execute two curl commands, one for each application. This can not be done is a single command.
Its totally transparent for single naming strategy.
If `deployment_name` or `deployment_names` is not set, then `application_name` is a candidate for names split.
=> notify deployment with roll-up naming

Command/NotifyDeploymentCommand.php
The command was always failing because we treated the return value from `performRequest` as an integer
=> Fixed bugs in the command

Listener/RequestListener.php, README.md, Resources/config/services.xml, Silex/EkinoNewRelicServiceProvider.php, Tests/Listener/RequestListenerTest.php
This is the registered events in standard symfony.
Listener Class Name | Priority
---------------------------- | ---------
ProfilerListener | 1024
TestSessionListener | 192
SessionListener | 128
RouterListener | 32
LocaleListener | 16
Firewall | 8
([source](http://symfony.com/doc/current/reference/dic_tags.html#kernel-request))
Current behavior is to set the application and transaction name after the firewall. This will lead to that transactions interrupted by the firewall are not getting the proper application key. They will be registered with the license key defined in php.ini. (See #87)
This PR splits the `RequestListener::onCoreRequest` into three functions. One that names the application, one that ignores the transaction and one that names the transaction. The one that set the …
=> Changed the event priorities

Listener/RequestListener.php
Calling `newrelic_set_appname()` seems to lose current transaction.
Since `Newrelic::$name` is always filled with the ini settings (#88) then there is no way to avoid the `newrelic_set_appname()` call.
But because the method call is quite late in the php process, then Newrelic decrease the "Time spent in PHP" (and increase the "Request queueing time"), which is wrong. A similar problem was described 2y ago in #24
A solution is not to call the method before but to **not call it at all** if the name doesn't differ from the ini config (and let the extension do its job). I'm not sure this is the right thing to do but at least it works for us. I've only covered the `RequestListener` part.
=> Call newrelic_set_appname() only if different from ini configuration

NewRelic/NewRelicInteractor.php
Having these values type hinted to a string or a double makes it impossible to use New Relic Insights to determine averages for values that should be treated as integers for custom parameters
=> Remove type hinting for values

.travis.yml, Tests/bootstrap.php, composer.json
This pull makes some updates to the CI integration and `composer.json` for Symfony 2.8 & 3.0.
- `composer.json` is updated to allow 3.0 packages
- Travis-CI updates:
- Default test branch is now the 2.7 LTS branch
- Test support is removed for the EOL 2.5 branch
- Test support is added for the 2.8 and 3.0 development branches 
- The `COMPOSER_FLAGS` environmental variable wasn't used, implemented it
- Since `--prefer-lowest` isn't an option on `composer require`, adjusted the install script to call `composer update` which supports it
- Register `Twig_Autoloader` if Twig hasn't registered to Composer's autoloader (required for the `--prefer-lowest` run)
=> Symfony 2.8 & 3.0 Support

README.md
A very simple update on path to get API keys on New Relic website.
=> Update path to get API Keys on NewRelic's dashboard.

README.md
* Use `Symfony` instead of `Symfony2`
* Minor formatting issues with some `<code>` elements
=> Minor changes to the docs

Listener/CommandListener.php
Look like the call to `newrelic_set_appname` resets `newrelic_ignore_transaction`
Si PR move the call to `ignoreTransaction` after the call to `setApplicationName` in command listener
=> Move ignoreTransaction after setApplicationName

.travis.yml, DependencyInjection/EkinoNewRelicExtension.php, Exception/ThrowableException.php, Listener/CommandListener.php, Makefile, Resources/config/services.xml, Silex/EkinoNewRelicServiceProvider.php, Tests/Listener/CommandListenerTest.php, composer.json
Given I need php 7 and Symfony 3.3 to fully test this feature, I also made few changes in the travis.yml file.
Tell me if you prefer a separate PR
=> Replace deprecated ConsoleException by ConsolerError

.travis.yml, README.md, Twig/NewRelicExtension.php, composer.json
I'd propose to release this PR and #118 as version 1.4 and then remove support for outdated php versions for 1.5 version.
=> Use psr-4 autoloading, remove EOL symfony versions

Listener/ResponseListener.php, NewRelic/BlackholeInteractor.php, NewRelic/LoggingInteractorDecorator.php, NewRelic/NewRelic.php, NewRelic/NewRelicInteractor.php, NewRelic/NewRelicInteractorInterface.php, Tests/Listener/ResponseListenerTest.php, Tests/NewRelic/NewRelicTest.php
PR to implement [inserting custom events via New Relic APM agent](https://docs.newrelic.com/docs/insights/new-relic-insights/adding-querying-data/inserting-custom-events-new-relic-apm-agents).
> Note: `newrelic_record_custom_event()` is available via the PHP agent as of v4.18.
In order to allow for multiple custom events with the same name in a single transaction, the custom events are stored on the `NewRelic` object as a multi-dimensional array, where the top-level array keys are the event names, and the nested arrays are the individual event attributes.
This differs slightly from the format used when sending custom events through the [Insights API](https://docs.newrelic.com/docs/insights/new-relic-insights/adding-querying-data/insert-custom-events-insights-api#json-format), but aligns …
=> Inserting custom events via New Relic agent

DependencyInjection/Compiler/MonologHandlerPass.php, DependencyInjection/Configuration.php, DependencyInjection/EkinoNewRelicExtension.php, EkinoNewRelicBundle.php, Logging/AutoHandler.php, README.md, Resources/config/services.xml, Tests/DependencyInjection/Compiler/MonologHandlerPassTest.php, Tests/DependencyInjection/EkinoNewRelicExtensionTest.php, composer.json
Provide a simple way to configure Monolog's NewRelicHandler
```yaml
ekino_new_relic:
log_logs: ~
```
or a more advanced usage
```yaml
ekino_new_relic:
log_logs:
level: warning
channels: [app, event]
service: ekino.new_relic.logs_handler.auto
```
TODO:
=> Add a log handler

DependencyInjection/Configuration.php, DependencyInjection/EkinoNewRelicExtension.php, NewRelic/AutoInteractor.php, README.md, Resources/config/services.xml, Tests/DependencyInjection/EkinoNewRelicExtensionTest.php
This will fix #127. 
-------
EDIT: 
I know that this is super weird. But checking #127 and possible #82 this make sense. 
The use case is when you have your deployed application with the container built, and then for some reason you unload the NewRelic extension (strange, yes). 
If you have this scenario, then you want to postpone the decision of using blackhole or not to runtime instead of build time.
=> Allow you to specify an interactor service

Listener/ResponseListener.php, Tests/Listener/ResponseListenerTest.php
Hi,
This PR should ensure that only master requests are handled by the `ResponseListener`. Sub-requests should be ignored.
I think that we need to avoid sub-requests because we only care about [master requests](https://github.com/ekino/EkinoNewRelicBundle/blob/master/Listener/RequestListener.php#L125) when starting NR transactions. That means that we must [end transaction](https://github.com/ekino/EkinoNewRelicBundle/blob/00f68a6bf836afeee9d83ac5e6b4087b89370b89/Listener/ResponseListener.php#L118) only if the request is a master one. If we process sub-requests in `ResponseListener` then we will accidentally, prematurely, end the master request transaction.
In other words, we always need to process _only_ master requests. This is already the case with `RequestListener` and now I fixed …
=> Only master requests should be processed by the ResponseListener.

DependencyInjection/Compiler/MonologHandlerPass.php, Tests/DependencyInjection/Compiler/MonologHandlerPassTest.php
Fixes an issue with DIC compilation where the
`ekino.new_relic.logs_handler` service is not registered when the
log_logs config is disabled.
=> Only register the logs_handler if enabled

Command/NotifyDeploymentCommand.php
Parameter expects boolean, not integer
https://secure.php.net/manual/en/function.file-get-contents.php
=> Deployment notification command broken on php 7.2

DependencyInjection/Configuration.php, NewRelic/Config.php
As per Configuration the config `application_name` can be null.
api_key is not a boolean, and should be optional
=> Fix application_name and api_key nullable

NewRelic/NewRelicInteractor.php
Im doing this to avoid sending an empty string to `newrelic_start_transaction`
=> Do not use second arguement if not set

Resources/config/deprecation_listener.xml
Right now the deprecation feature does not work. 
https://github.com/ekino/EkinoNewRelicBundle/blob/2.0.0-beta2/EkinoNewRelicBundle.php#L34
=> make the deprecation listener public

CHANGELOG.md, DependencyInjection/Compiler/MonologHandlerPass.php, DependencyInjection/Configuration.php, DependencyInjection/EkinoNewRelicExtension.php, README.md, Tests/DependencyInjection/Compiler/MonologHandlerPassTest.php
Allows a configuration similar to the MonologBUndle's one (http://symfony.com/doc/current/logging/channels_handlers.html#yaml-specification)
```
channels: ~    # Include all the channels  
channels: foo  # Include only channel 'foo' 
channels: '!foo' # Include all channels, except 'foo' 
channels: [foo, bar]   # Include only channels 'foo' and 'bar' 
channels: ['!foo', '!bar'] # Include all channels, except 'foo' and 'bar'
```
Most of the code come from the MonologBundle itself (https://github.com/symfony/monolog-bundle/tree/master/DependencyInjection)
=> Fine tuning for Monolog Configuration

CHANGELOG.md, NewRelic/NewRelicInteractor.php
I run the latest new relic extension that I can install with Yum. And I get the following error:
> Type error: Return value of Ekino\NewRelicBundle\NewRelic\NewRelicInteractor::disableAutoRUM() must be of the type boolean, null returned
According to the [docs](https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_disable_autorum) it should always return true... But that is not the case. I will contact the support about this. 
However, This is a fix that make sure it always works. It looks weird but it is according to the current new relic docs.
=> Make sure we always return true

NewRelic/AdaptiveInteractor.php, NewRelic/BlackholeInteractor.php, NewRelic/LoggingInteractorDecorator.php, NewRelic/NewRelicInteractor.php, NewRelic/NewRelicInteractorInterface.php
This is a follow-up form https://github.com/ekino/EkinoNewRelicBundle/pull/193,
NewRelic updated their API after I made this comment: https://discuss.newrelic.com/t/php-newrelic-disable-autorum-does-not-return-boolean/57148
=> Update interface return value to match the new NewRelic API

DependencyInjection/Compiler/MonologHandlerPass.php, DependencyInjection/EkinoNewRelicExtension.php, Tests/DependencyInjection/Compiler/MonologHandlerPassTest.php, Tests/DependencyInjection/EkinoNewRelicExtensionTest.php
Move the service configuration from Extension to CompilerPass as the extension is only able to see it own services/alias and is not able to see the application's one
=> Fix monolog external service

NewRelic/Config.php
PHP is deprecating chaining ternary operators for PHP 7.4, and will throw an error in PHP 8+ ([see this RFC](https://wiki.php.net/rfc/ternary_associativity)).
As shown in [this gist](https://gist.github.com/nikic/b6214f87b0e4a7c6fe26919ac849194f) searching for possible issues in the top 1000 Packagist repos, `EkinoNewRelicBundle` has two occurences of this syntax. I added parenthesis as recommended in the RFC to avoid any warning and future errors.
=> Fix left-associative ternary deprecation warnings for PHP 7.4

DependencyInjection/Configuration.php, Twig/NewRelicExtension.php
Closes #217
Some Twig classes are deprecated thus we have to stop using them, such as:
- `\Twig_Environment`
- `\Twig_Extension`
- `\TwigFilter`
This PR also causes adds `phpunit/phpunit` ^7.5 as an explicit dev dependency, since people might use a global phpunit ^8 dependency and this version is incompatible with the tests (but fixing the tests themselves would be out of the scope of this PR).
=> Fix twig-related deprecation errors

composer.json
We don’t need that. None of our code depends on it.  It is just a tool.
=> Remove cs fixer

.travis.yml, Listener/ExceptionListener.php, Listener/RequestListener.php, Listener/ResponseListener.php, Tests/BundleInitializationTest.php, Tests/DependencyInjection/Compiler/MonologHandlerPassTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/EkinoNewRelicExtensionTest.php, Tests/Listener/DeprecationListenerTest.php, Tests/Listener/ExceptionListenerTest.php, Tests/Listener/RequestListenerTest.php, Tests/Listener/ResponseListenerTest.php, Tests/NewRelic/LoggingInteractorDecoratorTest.php, Tests/Twig/NewRelicExtensionTest.php, composer.json, phpunit.xml.dist
Fix events renaming
- `FilterResponseEvent` => `ResponseEvent`
- `GetResponseEvent` => `ResponseEvent`
- `GetResponseForExceptionEvent` => `ExceptionEvent`
Bump `matthiasnoback/symfony-dependency-injection-test` to `^4.0` to allow symfony 5.0 in tests
=> Fix compatibility issue with symfony 5.0

CHANGELOG.md, Command/NotifyDeploymentCommand.php, DependencyInjection/Configuration.php, DependencyInjection/EkinoNewRelicExtension.php, NewRelic/Config.php, README.md, Tests/NewRelic/ConfigTest.php
The API host was hardcoded and deployment notification did not work for the EU region datacenter, now it can be set by setting the api_host configuration property.
This fix closes the https://github.com/ekino/EkinoNewRelicBundle/issues/231 issue
=> Feature api host in config

Listener/ExceptionListener.php, Listener/RequestListener.php, Listener/ResponseListener.php
With PHP 7.4 and preloading, peple reported the following error:
Noticed exception 'ErrorException' with message 'Warning: Cannot declare class Ekino\NewRelicBundle\Listener\KernelExceptionEvent, because the name is already in use' in /app/vendor/ekino/newrelic-bundle/Listener/ExceptionListener.php:55
I guess it happens when the class `KernelExceptionEvent` exists (in cache) but not the ExceptionListener.
This PR checks if the class already exists before creating the alias
=> Fix class loaded twice
