ekino/EkinoNewRelicBundle

Resources/config/services.xml, Tests/Twig/NewRelicExtensionTest.php, Twig/NewRelicExtension.php
Also wrong method names and missing tag so twig recognizes this as an extension. Really sorry, tested and everything works now as expected.
=> Add fixes for method name and service tag for twig

Command/NotifyDeploymentCommand.php
This PR allows to display the original response error message. Example : 
``Deployment not recorded: Received HTTP status 422``
becomes
``Deployment not recorded. Received "422 Application MyApp does not exist."``
=> Improve command error reporting

composer.json
=> Bump dev version

Twig/NewRelicExtension.php
=> Removed Twig deprecated features.

README.md
READMEing about who to get one in NR dashboard, and how not confusing it with the license key.
=> How to get an API key

SILEX.rst, Silex/EkinoNewRelicServiceProvider.php
Silex support for parameters introduced in https://github.com/ekino/EkinoNewRelicBundle/pull/34.
Documentation for Silex updated.
=> Add license_key and xmit parameters for Silex

README.md
The documentation was missing the default values which made it pretty confusing.
=> Document default config values in README.md

NewRelic/NewRelicInteractorInterface.php
Sorry for small PR, it annoyed me :)
=> Make PHPDoc fit the method signature

DependencyInjection/Configuration.php, DependencyInjection/EkinoNewRelicExtension.php, README.md, Resources/config/services.xml
Currently the bundle actually has a hard dependency on Twig. 
With this PR you may opt-out of using Twig.
=> Make sure you can use the bundle without having twig installed

NewRelic/BlackholeInteractor.php, NewRelic/LoggingInteractorDecorator.php, NewRelic/NewRelicInteractor.php, NewRelic/NewRelicInteractorInterface.php
=> Add method to interface and interactor

Tests/Listener/ResponseListenerTest.php, Tests/Twig/NewRelicExtensionTest.php
Fixed issue @Tobion commented here: https://github.com/ekino/EkinoNewRelicBundle/pull/130/files
=> Converted "public function setUp" to protected.

Command/NotifyDeploymentCommand.php, DependencyInjection/EkinoNewRelicExtension.php, NewRelic/NewRelic.php, NewRelic/NewRelicInteractorInterface.php, Resources/config/services.xml
Removed use of container parameters and properly register the command as a service. I also helped the auto write feature to find our services.
=> Minor code cleanup and documentation fixes

.travis.yml
I know this looks weird with my logger and there is no way to see the results. 
Im working on a service that show integration tests with frameworks. I'll remove it if we do not like it in our travis.yml.
=> Adding scrutinizer and tnyholm logger

Logging/AdaptiveHandler.php, NewRelic/AdaptiveInteractor.php, Resources/config/services.xml, Tests/DependencyInjection/EkinoNewRelicExtensionTest.php
That name is more descriptive, right?
Do we have any other suggestions?
=> Renamed "AutoHandler" and "AutoInteractor" to "Adaptive*"

NewRelic/LoggingInteractorDecorator.php
This PR conforms the logging decorator to the interface it implements
=> Fix the logging decorator function signatures

.gitignore, .php_cs, .travis.yml, composer.json
=> WIP Trigger CS fixer from travis

Listener/CommandListener.php, Listener/ExceptionListener.php, Listener/RequestListener.php, Listener/ResponseListener.php, Resources/config/exception_listener.xml, Resources/config/http_listener.xml, Tests/Listener/ResponseListenerTest.php
Because much more easy to read IMO.
Remove useless comments too
=> Switch eventListener to eventSubscriber

.php_cs, Command/NotifyDeploymentCommand.php, DependencyInjection/Compiler/MonologHandlerPass.php, DependencyInjection/Configuration.php, DependencyInjection/EkinoNewRelicExtension.php, EkinoNewRelicBundle.php, Exception/DeprecationException.php, Logging/AdaptiveHandler.php, NewRelic/AdaptiveInteractor.php, Tests/DependencyInjection/Compiler/MonologHandlerPassTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/Listener/CommandListenerTest.php, Tests/Listener/DeprecationListenerTest.php, Tests/Listener/RequestListenerTest.php, Tests/Listener/ResponseListenerTest.php, Tests/NewRelic/ConfigTest.php, Tests/NewRelic/LoggingInteractorDecoratorTest.php, Tests/TransactionNamingStrategy/ControllerNamingStrategyTest.php, Tests/Twig/NewRelicExtensionTest.php, TransactionNamingStrategy/ControllerNamingStrategy.php, TransactionNamingStrategy/RouteNamingStrategy.php, TransactionNamingStrategy/TransactionNamingStrategyInterface.php
Probalby need to cleanup all methods wit strict typehint before merging this one.
=> Use strict

UPGRADE-2.0.md
=> Add a documentation to help user to migrate to 2.0

DependencyInjection/EkinoNewRelicExtension.php
We should not overwrite existing names.
=> Add default "deployment_names"

README.md
https://github.com/ekino/EkinoNewRelicBundle/blob/master/DependencyInjection/Configuration.php#L96
=> Moved "intrument" to under "http"

CHANGELOG.md, DependencyInjection/EkinoNewRelicExtension.php, README.md, Tests/BundleInitializationTest.php
=> Use "adaptive" interactor as default.

CHANGELOG.md
Another beta with fixes from the past 2 weeks.
=> Prepare for Beta 5

DependencyInjection/Configuration.php
This will (potentially) fix #198
FYI: @redayoub
=> Type cast to string

.prettyci.composer.json, .travis.yml
=> Remove php-cs-fixer from travis

EkinoNewRelicBundle.php
Alternative to https://github.com/ekino/EkinoNewRelicBundle/pull/208
=> Unregister DeprecationHandler on shutdown

NewRelic/LoggingInteractorDecorator.php
This will help to debug when you don't have a `dev` environment on Newrelic and it's just an improvement of what is already there.
=> Add more detail/context when Logging Newrelic transactions

Listener/RequestListener.php, Tests/Listener/RequestListenerTest.php
=> Fix wrong event typehinted in RequestListener
